version: '3.6'

services:
  web:
    image: webdevops/php-apache:7.4
    restart: always
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- ../user_cyb10101/.composer/cache:/home/application/.composer/cache
      #- ../user_cyb10101/.ssh:/home/application/.ssh

    environment:
      - VIRTUAL_HOST=cyb10101.de,www.cyb10101.de
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
      - LETSENCRYPT_HOST=cyb10101.de,www.cyb10101.de

      - WEB_DOCUMENT_ROOT=/app/public

      # Don't forget to connect via ./start.sh
#      - APPLICATION_UID=${APPLICATION_UID:-1000}
#      - APPLICATION_GID=${APPLICATION_GID:-1000}

      # SSL: Use default cert from global-nginx-proxy
      #- CERT_NAME=default
      # SSL: Do not a redirect in global-nginx-proxy, if you use another port than 443
      - HTTPS_METHOD=noredirect
    working_dir: /app

networks:
  default:
    external:
      name: global
