version: '3.8'
services:
  nextcloud:
    image: nextcloud
    restart: always
    volumes:
      - ./.docker/nextcloud:/var/www/html
    environment:
      - VIRTUAL_HOST=nextcloud.server.org
      - LETSENCRYPT_HOST=nextcloud.server.org

      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=global-db

      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=password
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.server.org
      - OVERWRITEPROTOCOL=https

      - SMTP_HOST=mail.server.org
      - SMTP_SECURE=ssl
      - SMTP_PORT=465
      - SMTP_AUTHTYPE=LOGIN
      - SMTP_NAME=no-reply@server.org
      - SMTP_PASSWORD=password
      - MAIL_FROM_ADDRESS=no-reply
      - MAIL_DOMAIN=server.org
    working_dir: /var/www/html

  cron:
    image: nextcloud
    restart: always
    volumes:
      - ./.docker/nextcloud:/var/www/html
    entrypoint: /cron.sh

networks:
  default:
    external:
      name: global
